# Generated by Django 5.0.6 on 2024-06-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='redirect_url',
            field=models.URLField(default='https://ashewa.com'),
            preserve_default=False,
        ),
    ]
