# Generated by Django 5.0.6 on 2024-06-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_rename_url_site_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='token',
            field=models.CharField(default='4567890-0987t', max_length=1000),
            preserve_default=False,
        ),
    ]
